Repository chainer/chainercv, pull requests merged in 2018-10, with the labels that each got.

#701 make mask_to_bbox support all False mask
  chainercv/utils/mask/mask_to_bbox.py
  tests/utils_tests/mask_tests/test_mask_to_bbox.py
Labels: enhancement

#709 Fix installation of pycocotools
  .travis.yml
Labels: bug

#712 fix failing flake8
  chainercv/datasets/siamese_dataset.py
  chainercv/evaluations/eval_semantic_segmentation.py
Labels: bug

#720 Fix doc of TupleDataset
  chainercv/chainer_experimental/datasets/sliceable/tuple_dataset.py
Labels: document
