Repository chainer/chainercv, pull requests merged in 2018-09, with the labels that each got.

#686 use kwargs for ResBlock in pspnet
  chainercv/experimental/links/model/pspnet/pspnet.py
Labels: bug

#687 Fix coco instance dataset test
  chainercv/utils/testing/assertions/assert_is_instance_segmentation_dataset.py
  tests/datasets_tests/coco_tests/test_coco_instance_segmentation_dataset.py
Labels: bug

#689 refine transforms_tests/bbox_tests
  tests/transforms_tests/bbox_tests/test_crop_bbox.py
  tests/transforms_tests/bbox_tests/test_flip_bbox.py
  tests/transforms_tests/bbox_tests/test_resize_bbox.py
  tests/transforms_tests/bbox_tests/test_translate_bbox.py
Labels: enhancement

#692 add rotate_bbox
  chainercv/transforms/__init__.py
  chainercv/transforms/bbox/rotate_bbox.py
  docs/source/reference/transforms.rst
  tests/transforms_tests/bbox_tests/test_rotate_bbox.py
Labels: enhancement

#690 add rotate transforms for image
  chainercv/transforms/__init__.py
  chainercv/transforms/image/rotate.py
  docs/source/reference/transforms.rst
  tests/transforms_tests/image_tests/test_rotate.py
Labels: enhancement

#400 Add a test for OnlineProductsDataset
  chainercv/datasets/online_products/online_products_dataset.py
  tests/datasets_tests/test_online_products/test_online_products_dataset.py
Labels: no-compat

#656 Fix doc and style of SEResNet
  README.md
  chainercv/links/connection/seblock.py
  docs/source/license.rst
  docs/source/reference/links.rst
Labels: enhancement

#694 Use COCO2017
  chainercv/datasets/coco/coco_bbox_dataset.py
  chainercv/datasets/coco/coco_instance_segmentation_dataset.py
  chainercv/datasets/coco/coco_utils.py
  tests/datasets_tests/coco_tests/test_coco_bbox_dataset.py
  tests/datasets_tests/coco_tests/test_coco_instance_segmentation_dataset.py
Labels: enhancement

#700 fix doc badge link
  README.md
Labels: bug
