Repository chainer/chainercv, pull requests merged in 2018-02, with the labels that each got.

#522 list()/dict() -> []/{}
  chainercv/datasets/cityscapes/cityscapes_semantic_segmentation_dataset.py
  chainercv/datasets/cityscapes/cityscapes_test_image_dataset.py
  chainercv/datasets/cub/cub_keypoint_dataset.py
  chainercv/datasets/directory_parsing_label_dataset.py
  chainercv/datasets/online_products/online_products_dataset.py
  chainercv/datasets/voc/voc_bbox_dataset.py
  chainercv/extensions/evaluator/detection_voc_evaluator.py
  chainercv/extensions/evaluator/semantic_segmentation_evaluator.py
  chainercv/links/connection/conv_2d_bn_activ.py
  chainercv/links/model/faster_rcnn/faster_rcnn.py
  chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py
  chainercv/links/model/faster_rcnn/region_proposal_network.py
  chainercv/links/model/feature_predictor.py
  chainercv/links/model/pickable_sequential_chain.py
  chainercv/links/model/segnet/segnet_basic.py
  chainercv/links/model/ssd/multibox.py
  chainercv/links/model/ssd/multibox_coder.py
  chainercv/links/model/ssd/ssd.py
  chainercv/links/model/ssd/ssd_vgg16.py
  chainercv/links/model/ssd/transforms.py
  chainercv/utils/iterator/apply_prediction_to_iterator.py
  chainercv/utils/testing/constant_stub_link.py
  chainercv/visualizations/vis_bbox.py
  chainercv/visualizations/vis_semantic_segmentation.py
  docs/source/conf.py
  setup.py
  style_checker.py
  tests/extensions_tests/vis_report_tests/test_detection_vis_report.py
  tests/links_tests/model_tests/ssd_tests/test_multibox.py
  tests/links_tests/model_tests/ssd_tests/test_multibox_loss.py
  tests/links_tests/model_tests/test_pickable_sequential_chain.py
  tests/utils_tests/iterator_tests/test_apply_prediction_to_iterator.py
  tests/utils_tests/iterator_tests/test_progress_hook.py
  tests/utils_tests/iterator_tests/test_unzip.py
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_detection_link.py
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_semantic_segmentation_link.py
Labels: enhancement

#524 Add assert_is_point
  chainercv/utils/__init__.py
  chainercv/utils/testing/__init__.py
  chainercv/utils/testing/assertions/__init__.py
  chainercv/utils/testing/assertions/assert_is_point.py
  docs/source/reference/utils.rst
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_point.py
Labels: enhancement, test

#519 Dynamically import matplotlib.pyplot
  chainercv/extensions/vis_report/detection_vis_report.py
Labels: bug
