Repository chainer/chainercv, pull requests merged in 2018-04, with the labels that each got.

#549 Add dilate and bn_kwargs to Bottleneck and ResBlock
  chainercv/links/connection/conv_2d_activ.py
  chainercv/links/connection/conv_2d_bn_activ.py
  chainercv/links/model/resnet/resblock.py
Labels: enhancement

#548 Fix ResNets when initialW is specified
  chainercv/links/model/resnet/resnet.py
Labels: bug

#552 add mask_iou
  chainercv/utils/__init__.py
  chainercv/utils/mask/__init__.py
  chainercv/utils/mask/mask_iou.py
  docs/source/reference/utils.rst
  tests/utils_tests/mask_tests/test_mask_iou.py
Labels: feature

#557 Make dataset dependent part clear for SegNet example
  examples/segnet/train.py
Labels: enhancement

#556 Fix ade_label_names and ade_label_colors
  chainercv/datasets/ade20k/ade20k_utils.py
Labels: bug

#432 Add random_size_crop
  chainercv/transforms/__init__.py
  chainercv/transforms/image/random_sized_crop.py
  docs/source/reference/transforms.rst
  tests/transforms_tests/image_tests/test_random_sized_crop.py
Labels: feature

#565 bach -> batch
  tests/links_tests/connection_tests/test_conv_2d_bn_activ.py
Labels: document

#550 Fix build scripts not to include binary files and .pyx files
  MANIFEST.in
  setup.py
Labels: bug

#570 Improve sliceable tutorial
  docs/source/tutorial/sliceable.rst
Labels: document

#571 Support keys assign in GetterDataset
  chainercv/chainer_experimental/datasets/sliceable/getter_dataset.py
  chainercv/chainer_experimental/datasets/sliceable/sliceable_dataset.py
  chainercv/chainer_experimental/datasets/sliceable/tuple_dataset.py
  tests/chainer_experimental_tests/datasets_tests/sliceable_tests/test_getter_dataset.py
Labels: enhancement

#527 Add assert_is_point_dataset
  chainercv/utils/__init__.py
  chainercv/utils/testing/__init__.py
  chainercv/utils/testing/assertions/__init__.py
  chainercv/utils/testing/assertions/assert_is_bbox_dataset.py
  chainercv/utils/testing/assertions/assert_is_label_dataset.py
  chainercv/utils/testing/assertions/assert_is_point_dataset.py
  docs/source/reference/utils.rst
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_point_dataset.py
Labels: test

#573 Change the author email address
  setup.py
Labels: enhancement

#560 Support using vis_bbox together with vis_instance_segmentation
  chainercv/visualizations/colormap.py
  chainercv/visualizations/vis_bbox.py
  chainercv/visualizations/vis_instance_segmentation.py
  chainercv/visualizations/vis_semantic_segmentation.py
  tests/visualizations_tests/test_vis_bbox.py
  tests/visualizations_tests/test_vis_instance_segmentation.py
Labels: feature

#574 plot --> plt
  chainercv/extensions/vis_report/detection_vis_report.py
  chainercv/visualizations/vis_point.py
  chainercv/visualizations/vis_semantic_segmentation.py
  examples/detection/visualize_models.py
  examples/faster_rcnn/demo.py
  examples/segnet/demo.py
  examples/ssd/demo.py
Labels: enhancement

#528 Change name to CUBPointDataset and add tests
  chainercv/datasets/__init__.py
  chainercv/datasets/cub/cub_point_dataset.py
  chainercv/visualizations/vis_point.py
  docs/source/reference/datasets.rst
  tests/datasets_tests/cub_tests/test_cub_point_dataset.py
Labels: enhancement, no-compat, test

#572 Chainer 4.0.0
  .travis.yml
  README.md
  chainercv/extensions/vis_report/detection_vis_report.py
  chainercv/functions/psroi_pooling_2d.py
  chainercv/links/model/faster_rcnn/faster_rcnn.py
  chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py
  chainercv/links/model/faster_rcnn/region_proposal_network.py
  chainercv/links/model/faster_rcnn/utils/anchor_target_creator.py
  chainercv/links/model/faster_rcnn/utils/bbox2loc.py
  chainercv/links/model/faster_rcnn/utils/loc2bbox.py
  chainercv/links/model/faster_rcnn/utils/proposal_creator.py
  chainercv/links/model/faster_rcnn/utils/proposal_target_creator.py
  chainercv/links/model/feature_predictor.py
  chainercv/links/model/pixelwise_softmax_classifier.py
  chainercv/links/model/resnet/resnet.py
  chainercv/links/model/segnet/segnet_basic.py
  chainercv/links/model/ssd/gradient_scaling.py
  chainercv/links/model/ssd/multibox_coder.py
  chainercv/links/model/ssd/multibox_loss.py
  chainercv/links/model/ssd/ssd.py
  chainercv/utils/bbox/bbox_iou.py
  chainercv/utils/bbox/non_maximum_suppression.py
  chainercv/utils/mask/mask_iou.py
  chainercv/utils/mask/mask_to_bbox.py
  docs/requirements.txt
  examples/faster_rcnn/train.py
  examples/segnet/train.py
  examples/ssd/README.md
  examples/ssd/train.py
  examples/ssd/train_multi.py
  setup.py
  tests/functions_tests/test_psroi_pooling_2d.py
  tests/links_tests/connection_tests/test_conv_2d_activ.py
  tests/links_tests/connection_tests/test_conv_2d_bn_activ.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_region_proposal_network.py
  tests/links_tests/model_tests/faster_rcnn_tests/utils_tests/test_anchor_target_creator.py
  tests/links_tests/model_tests/faster_rcnn_tests/utils_tests/test_bbox2loc_loc2bbox.py
  tests/links_tests/model_tests/faster_rcnn_tests/utils_tests/test_proposal_creator.py
  tests/links_tests/model_tests/faster_rcnn_tests/utils_tests/test_proposal_target_creator.py
  tests/links_tests/model_tests/ssd_tests/test_multibox.py
  tests/links_tests/model_tests/ssd_tests/test_multibox_coder.py
  tests/links_tests/model_tests/ssd_tests/test_multibox_loss.py
  tests/links_tests/model_tests/ssd_tests/test_normalize.py
  tests/links_tests/model_tests/test_pickable_sequential_chain.py
  tests/utils_tests/bbox_tests/test_bbox_iou.py
  tests/utils_tests/bbox_tests/test_non_maximum_suppression.py
  tests/utils_tests/mask_tests/test_mask_iou.py
  tests/utils_tests/mask_tests/test_mask_to_bbox.py
  tests/utils_tests/testing_tests/test_constant_stub_link.py
Labels: enhancement

#577 fix _check_available in SBDInstanceSegmentationDataset
  chainercv/datasets/sbd/sbd_instance_segmentation_dataset.py
Labels: bug

#457 Use SliceableDataset
  chainercv/datasets/ade20k/ade20k_semantic_segmentation_dataset.py
  chainercv/datasets/ade20k/ade20k_test_image_dataset.py
  chainercv/datasets/camvid/camvid_dataset.py
  chainercv/datasets/cityscapes/cityscapes_semantic_segmentation_dataset.py
  chainercv/datasets/cityscapes/cityscapes_test_image_dataset.py
  chainercv/datasets/cub/cub_label_dataset.py
  chainercv/datasets/cub/cub_point_dataset.py
  chainercv/datasets/cub/cub_utils.py
  chainercv/datasets/directory_parsing_label_dataset.py
  chainercv/datasets/mixup_soft_label_dataset.py
  chainercv/datasets/online_products/online_products_dataset.py
  chainercv/datasets/sbd/sbd_instance_segmentation_dataset.py
  chainercv/datasets/siamese_dataset.py
  chainercv/datasets/voc/voc_bbox_dataset.py
  chainercv/datasets/voc/voc_instance_segmentation_dataset.py
  chainercv/datasets/voc/voc_semantic_segmentation_dataset.py
Labels: feature, no-compat

#576 Change vis_semantic_segmentation to take image
  chainercv/visualizations/vis_semantic_segmentation.py
  examples/segnet/demo.py
  tests/visualizations_tests/test_vis_semantic_segmentation.py
Labels: enhancement, no-compat

#580 Update to 0.9
  docs/source/conf.py
  setup.py
Labels: enhancement

#568 add FCIS ResNet101
  chainercv/__init__.py
  chainercv/experimental/__init__.py
  chainercv/experimental/links/__init__.py
  chainercv/experimental/links/model/__init__.py
  chainercv/experimental/links/model/fcis/__init__.py
  chainercv/experimental/links/model/fcis/fcis.py
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/experimental/links/model/fcis/utils/__init__.py
  chainercv/experimental/links/model/fcis/utils/mask_voting.py
  chainercv/utils/__init__.py
  chainercv/utils/testing/__init__.py
  chainercv/utils/testing/assertions/__init__.py
  chainercv/utils/testing/assertions/assert_is_instance_segmentation_link.py
  docs/source/reference/experimental.rst
  docs/source/reference/experimental/fcis.rst
  docs/source/reference/index.rst
  examples/fcis/demo.py
  examples/instance_segmentation/eval_sbd.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/utils_tests/test_mask_voting.py
Labels: feature

#587 update fcis variables names
  chainercv/experimental/links/model/fcis/fcis.py
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/experimental/links/model/fcis/utils/mask_voting.py
Labels: enhancement
