Repository chainer/chainercv, pull requests merged in 2018-05, with the labels that each got.

#584 Use `prob` more strictly inside SSD and Faster R-CNN
  chainercv/links/model/faster_rcnn/faster_rcnn.py
Labels: enhancement

#597 Fix hacking version
  .travis.yml
Labels: bug

#591 add prepare_pretrained_model
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py
  chainercv/links/model/resnet/resnet.py
  chainercv/links/model/segnet/segnet_basic.py
  chainercv/links/model/ssd/ssd_vgg16.py
  chainercv/links/model/vgg/vgg16.py
  chainercv/links/model/yolo/yolo_v2.py
  chainercv/links/model/yolo/yolo_v3.py
  chainercv/utils/__init__.py
  chainercv/utils/link.py
  docs/source/reference/utils.rst
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_faster_rcnn_vgg.py
  tests/links_tests/model_tests/resnet_tests/test_resnet.py
  tests/links_tests/model_tests/segnet_tests/test_segnet_basic.py
  tests/links_tests/model_tests/ssd_tests/test_ssd_vgg16.py
  tests/links_tests/model_tests/vgg_tests/test_vgg16.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_v2.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_v3.py
Labels: enhancement

#599 Improve pretrained tests
  chainercv/links/model/yolo/yolo_v2.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_faster_rcnn_vgg.py
  tests/links_tests/model_tests/resnet_tests/test_resnet.py
  tests/links_tests/model_tests/segnet_tests/test_segnet_basic.py
  tests/links_tests/model_tests/ssd_tests/test_ssd_vgg16.py
  tests/links_tests/model_tests/vgg_tests/test_vgg16.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_v2.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_v3.py
Labels: enhancement, test

#583 str --> string
  chainercv/datasets/directory_parsing_label_dataset.py
  chainercv/extensions/vis_report/detection_vis_report.py
  chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py
  chainercv/links/model/resnet/resnet.py
  chainercv/links/model/segnet/segnet_basic.py
  chainercv/links/model/ssd/ssd_vgg16.py
  chainercv/links/model/vgg/vgg16.py
  chainercv/links/model/yolo/yolo_v2.py
  chainercv/links/model/yolo/yolo_v3.py
  chainercv/utils/download.py
  chainercv/utils/image/read_image.py
  chainercv/utils/image/write_image.py
Labels: document

#606 add prob clipping for mask_voting
  chainercv/experimental/links/model/fcis/utils/mask_voting.py
Labels: bug

#607 Simplify mask voting
  chainercv/experimental/links/model/fcis/utils/mask_voting.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/utils_tests/test_mask_voting.py
Labels: enhancement

#609 add instance segmentation voc evaluator extensions
  chainercv/extensions/__init__.py
  chainercv/extensions/evaluator/instance_segmentation_voc_evaluator.py
  docs/source/reference/extensions.rst
  tests/extensions_tests/evaluator_tests/test_instance_segmentation_voc_evaluator.py
Labels: enhancement

#608 update fcis variable names
  chainercv/experimental/links/model/fcis/fcis.py
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/experimental/links/model/fcis/utils/mask_voting.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/utils_tests/test_mask_voting.py
Labels: enhancement

#441 Add exclude option to style_checker.py
  .travis.yml
  style_checker.py
Labels: enhancement

#619 ChainerMN 1.3
  README.md
  chainercv/links/model/ssd/multibox_loss.py
  environment.yml
Labels: enhancement

#617 use --foo-bar style in argparse
  examples/classification/eval_imagenet.py
  examples/segnet/train.py
  examples/ssd/README.md
  examples/ssd/train_multi.py
  examples/yolo/README.md
  examples/yolo/darknet2npz.py
Labels: enhancement

#618 Use loc, obj, conf in YOLO
  chainercv/links/model/yolo/yolo_base.py
  chainercv/links/model/yolo/yolo_v2.py
  chainercv/links/model/yolo/yolo_v3.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_base.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_v2.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_v3.py
Labels: enhancement

#623 Fix pickle issue in train_multi.py in SSD
  chainercv/chainer_experimental/datasets/sliceable/transform_dataset.py
  examples/ssd/train_multi.py
Labels: feature
