Repository chainer/chainercv, pull requests merged in 2018-03, with the labels that each got.

#529 Support None option for activ
  chainercv/links/connection/conv_2d_activ.py
  chainercv/links/connection/conv_2d_bn_activ.py
  tests/links_tests/connection_tests/test_conv_2d_activ.py
  tests/links_tests/connection_tests/test_conv_2d_bn_activ.py
Labels: enhancement

#530 add tuple check to style_checker
  style_checker.py
Labels: test

#505 Add SiameseDataset
  chainercv/datasets/__init__.py
  chainercv/datasets/siamese_dataset.py
  docs/source/reference/datasets.rst
  tests/datasets_tests/test_siamese_dataset.py
Labels: feature

#523 Improve apply_prediction
  chainercv/extensions/evaluator/detection_voc_evaluator.py
  chainercv/extensions/evaluator/semantic_segmentation_evaluator.py
  chainercv/utils/__init__.py
  chainercv/utils/iterator/__init__.py
  chainercv/utils/iterator/apply_prediction_to_iterator.py
  chainercv/utils/iterator/apply_to_iterator.py
  chainercv/utils/iterator/progress_hook.py
  docs/source/reference/utils.rst
  examples/classification/eval_imagenet.py
  examples/detection/eval_voc07.py
  examples/segnet/eval_camvid.py
  tests/utils_tests/iterator_tests/test_apply_prediction_to_iterator.py
  tests/utils_tests/iterator_tests/test_apply_to_iterator.py
  tests/utils_tests/iterator_tests/test_progress_hook.py
Labels: enhancement, no-compat

#531 Add a simple example for SiameseDataset
  chainercv/datasets/siamese_dataset.py
Labels: document

#321 Add ResNet
  README.md
  chainercv/links/__init__.py
  chainercv/links/model/resnet/__init__.py
  chainercv/links/model/resnet/resblock.py
  chainercv/links/model/resnet/resnet.py
  chainercv/links/model/vgg/vgg16.py
  docs/source/reference/links.rst
  docs/source/reference/links/resnet.rst
  examples/classification/README.md
  examples/classification/eval_imagenet.py
  examples/resnet/README.md
  examples/resnet/caffe2npz.py
  tests/links_tests/model_tests/resnet_tests/test_resnet.py
Labels: feature

#525 vis_keypoint --> vis_point
  chainercv/visualizations/__init__.py
  chainercv/visualizations/vis_keypoint.py
  chainercv/visualizations/vis_point.py
  docs/source/reference/visualizations.rst
  tests/visualizations_tests/test_vis_point.py
Labels: no-compat

#534 Fix the range of offset in random_crop
  chainercv/transforms/image/random_crop.py
Labels: bug

#533 Fix pretrained weight for ResNet
  chainercv/links/model/resnet/resnet.py
  examples/classification/README.md
  examples/classification/eval_imagenet.py
  examples/resnet/caffe2npz.py
Labels: bug

#540 Add VOC and SBD instance segmentation dataset
  README.md
  chainercv/datasets/__init__.py
  chainercv/datasets/sbd/__init__.py
  chainercv/datasets/sbd/sbd_instance_segmentation_dataset.py
  chainercv/datasets/sbd/sbd_utils.py
  chainercv/datasets/voc/voc_instance_segmentation_dataset.py
  chainercv/datasets/voc/voc_utils.py
  chainercv/utils/__init__.py
  chainercv/utils/testing/__init__.py
  chainercv/utils/testing/assertions/__init__.py
  chainercv/utils/testing/assertions/assert_is_instance_segmentation_dataset.py
  docs/source/reference/datasets.rst
  docs/source/reference/utils.rst
  environment.yml
  tests/datasets_tests/sbd_tests/test_sbd_instance_segmentation_dataset.py
  tests/datasets_tests/voc_tests/test_voc_instance_segmentation_dataset.py
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_instance_segmentation_dataset.py
Labels: feature

#541 Add vis instance segmentation func
  chainercv/visualizations/__init__.py
  chainercv/visualizations/vis_instance_segmentation.py
  docs/source/reference/visualizations.rst
  tests/visualizations_tests/test_vis_instance_segmentation.py
Labels: feature

#544 Do not use vis_image in vis_instance_segmentation
  chainercv/visualizations/vis_instance_segmentation.py
Labels: enhancement

#545 Add PSROIPooling Function
  chainercv/functions/__init__.py
  chainercv/functions/psroi_pooling_2d.py
  docs/source/reference/functions.rst
  docs/source/reference/index.rst
  tests/functions_tests/test_psroi_pooling_2d.py
Labels: feature

#542 fix doc
  chainercv/datasets/cityscapes/cityscapes_semantic_segmentation_dataset.py
  chainercv/datasets/directory_parsing_label_dataset.py
  chainercv/datasets/siamese_dataset.py
  chainercv/links/model/feature_predictor.py
Labels: document
