Repository chainer/chainercv, pull requests merged in 2018-12, with the labels that each got.

#740 Use PIL and cv2 for rotate
  chainercv/__init__.py
  chainercv/transforms/image/rotate.py
  environment.yml
  environment_minimum.yml
  tests/transforms_tests/image_tests/test_rotate.py
Labels: enhancement, no-compat

#751 Fix resnet50 fb url
  chainercv/links/model/resnet/resnet.py
Labels: bug

#752 fix typo in mxnet2npz.py script
  examples/fcis/mxnet2npz.py
Labels: bug

#754 return empty bbox when input mask is empty in mask_to_bbox
  chainercv/utils/mask/mask_to_bbox.py
Labels: bug

#748 Refactor PSPNet, support Res50 backbone and ImageNet pretrained weights
  chainercv/experimental/links/__init__.py
  chainercv/experimental/links/model/pspnet/__init__.py
  chainercv/experimental/links/model/pspnet/pspnet.py
  docs/source/reference/experimental/pspnet.rst
  tests/experimental_tests/links_tests/model_tests/pspnet_tests/test_pspnet.py
Labels: feature
