Repository chainer/chainercv, pull requests merged in 2018-11, with the labels that each got.

#711 Add YOLOv2 tiny
  chainercv/experimental/links/__init__.py
  chainercv/experimental/links/model/yolo/__init__.py
  chainercv/experimental/links/model/yolo/yolo_v2_tiny.py
  chainercv/links/model/yolo/__init__.py
  chainercv/links/model/yolo/yolo_base.py
  chainercv/links/model/yolo/yolo_v2.py
  docs/source/reference/experimental/yolo.rst
  docs/source/reference/links/yolo.rst
  examples/detection/README.md
  examples/detection/eval_voc07.py
  examples/detection/visualize_models.py
  examples/yolo/README.md
  examples/yolo/darknet2npz.py
  examples/yolo/demo.py
  tests/experimental_tests/links_tests/model_tests/yolo_tests/test_yolo_v2_tiny.py
Labels: feature

#713 Make backends of read_image and resize selectable
  chainercv/__init__.py
  chainercv/transforms/image/resize.py
  chainercv/utils/image/read_image.py
  chainercv/utils/link.py
  tests/links_tests/model_tests/ssd_tests/test_random_distort.py
  tests/links_tests/model_tests/ssd_tests/test_resize_with_random_interpolation.py
  tests/transforms_tests/image_tests/test_resize.py
  tests/utils_tests/image_tests/test_read_image.py
Labels: feature

#722 Fix README
  examples/detection/README.md
  examples/ssd/README.md
  examples/yolo/README.md
Labels: document

#723 use cupy.RawKernel in non_maximum_suppression
  chainercv/utils/bbox/non_maximum_suppression.py
Labels: enhancement

#725 raise error when year=2017 and split in [minival, valminusminival]
  chainercv/datasets/coco/coco_bbox_dataset.py
  chainercv/datasets/coco/coco_instance_segmentation_dataset.py
Labels: enhancement

#726 Add make_shift
  chainercv/chainer_experimental/__init__.py
  chainercv/chainer_experimental/training/__init__.py
  chainercv/chainer_experimental/training/extensions/__init__.py
  chainercv/chainer_experimental/training/extensions/make_shift.py
  docs/source/reference/chainer_experimental.rst
  docs/source/reference/chainer_experimental/extensions.rst
  tests/chainer_experimental_tests/training_tests/__init__.py
  tests/chainer_experimental_tests/training_tests/extensions_tests/__init__.py
  tests/chainer_experimental_tests/training_tests/extensions_tests/test_make_shift.py
Labels: feature

#728 Remove version specification of OpenCV
  environment.yml
Labels: enhancement

#729 use scales (tuple of floats) in region_proposal_network
  chainercv/links/model/faster_rcnn/faster_rcnn.py
  chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py
  chainercv/links/model/faster_rcnn/region_proposal_network.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_faster_rcnn.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_region_proposal_network.py
Labels: enhancement

#732 Fix typo in transforms/image
  chainercv/transforms/image/random_expand.py
Labels: document

#733 fix typo in transforms/image/resize_contain.py
  chainercv/transforms/image/resize_contain.py
Labels: document

#739 Add interpolation and fill options to rotate
  chainercv/transforms/image/rotate.py
  tests/transforms_tests/image_tests/test_rotate.py
Labels: feature, no-compat

#736 Add COCOSemanticSegmentationDataset
  chainercv/datasets/__init__.py
  chainercv/datasets/coco/coco_bbox_dataset.py
  chainercv/datasets/coco/coco_instance_segmentation_dataset.py
  chainercv/datasets/coco/coco_semantic_segmentation_dataset.py
  chainercv/datasets/coco/coco_utils.py
  docs/source/reference/datasets.rst
  tests/datasets_tests/coco_tests/test_coco_semantic_segmentation_dataset.py
Labels: feature

#741 add table in COCOInstanceSegmentationDataset
  chainercv/datasets/coco/coco_instance_segmentation_dataset.py
Labels: document

#745 Stop extracting dataset when ADE20k is extracted already
  chainercv/datasets/ade20k/ade20k_utils.py
Labels: bug

#742 Use chainer.global_config in doc
  chainercv/transforms/image/resize.py
  chainercv/utils/image/read_image.py
Labels: document

#436 Add ResNet training code
  chainercv/links/model/resnet/resnet.py
  examples/classification/README.md
  examples/classification/eval_imagenet.py
  examples/classification/train_imagenet_multi.py
Labels: feature

#708 Add examples tests
  examples/faster_rcnn/README.md
  examples/faster_rcnn/train.py
  examples/ssd/train.py
  examples/ssd/train_multi.py
  examples_tests/detection_tests/test_eval_voc07.sh
  examples_tests/detection_tests/test_visualize_models.sh
  examples_tests/faster_rcnn_tests/test_demo.sh
  examples_tests/faster_rcnn_tests/test_train.sh
  examples_tests/semantic_segmentation_tsets/test_eval_camvid.sh
  examples_tests/semantic_segmentation_tsets/test_eval_cityscapes.sh
  examples_tests/semantic_segmentation_tsets/test_eval_cityscapes_multi.sh
  examples_tests/ssd_tests/test_demo.sh
  examples_tests/ssd_tests/test_train.sh
  examples_tests/ssd_tests/test_train_multi.sh
Labels: feature, test

#746 Fix VOCSemanticSegmentationDataset bug with cv2
  chainercv/datasets/voc/voc_semantic_segmentation_dataset.py
Labels: bug
