Repository chainer/chainercv, pull requests merged in 2018-06, with the labels that each got.

#610 Add inference part of PSPNet
  .pep8
  chainercv/experimental/links/__init__.py
  chainercv/experimental/links/model/pspnet/__init__.py
  chainercv/experimental/links/model/pspnet/pspnet.py
  chainercv/experimental/links/model/pspnet/transforms.py
  chainercv/links/connection/conv_2d_bn_activ.py
  docs/source/reference/experimental.rst
  docs/source/reference/experimental/pspnet.rst
  examples/pspnet/README.md
  examples/pspnet/caffe2npz.py
  examples/pspnet/caffe_pb2.py
  examples/pspnet/demo.py
  examples/pspnet/weights/pspnet101_cityscapes_713.prototxt
  examples/segnet/README.md
  examples/semantic_segmentation/README.md
  examples/semantic_segmentation/eval_camvid.py
  examples/semantic_segmentation/eval_cityscapes.py
  setup.cfg
  tests/experimental_tests/links_tests/model_tests/pspnet_tests/test_convolution_crop.py
  tests/experimental_tests/links_tests/model_tests/pspnet_tests/test_pspnet.py
Labels: feature

#630 Add PSPNet to README
  README.md
Labels: document

#632 Add FCIS to README
  README.md
Labels: document

#629 multi GPU evaluation of semantic segmentation
  examples/semantic_segmentation/README.md
  examples/semantic_segmentation/eval_cityscapes_multi.py
Labels: feature

#631 Note pretrained models' license
  docs/source/index.rst
  docs/source/license.rst
Labels: document

#585 Add naming convention doc
  docs/source/index.rst
  docs/source/naming_convention.rst
Labels: document

#635 Update 0.10
  docs/source/conf.py
  setup.py
Labels: enhancement

#450 Check that assert_is_bbox passes 0 sized bbox
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_bbox.py
Labels: test

#451 Check that zero-sized bounding box can be generated by generate_random_bbox
  tests/utils_tests/testing_tests/test_generate_random_bbox.py
Labels: test

#452 Change assert_is_bbox_dataset to pass with zero-sized bbox
  chainercv/utils/testing/assertions/assert_is_bbox_dataset.py
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_bbox_dataset.py
Labels: test

#453 Add COCOBboxDataset
  chainercv/datasets/__init__.py
  chainercv/datasets/coco/__init__.py
  chainercv/datasets/coco/coco_bbox_dataset.py
  chainercv/datasets/coco/coco_utils.py
  docs/source/reference/datasets.rst
  tests/datasets_tests/coco_tests/test_coco_bbox_dataset.py
Labels: feature

#639 Fix typo in COCOBBoxDataset
  chainercv/datasets/coco/coco_bbox_dataset.py
Labels: bug

#456 Add eval_detection_coco
  .travis.yml
  chainercv/evaluations/__init__.py
  chainercv/evaluations/eval_detection_coco.py
  docs/source/_static/css/modified_theme.css
  docs/source/reference/evaluations.rst
  tests/evaluations_tests/test_eval_detection_coco.py
Labels: feature

#642 Add Ogawa as author
  setup.py
Labels: document

#645 Fix doc of eval_detection_coco
  chainercv/evaluations/eval_detection_coco.py
Labels: document

#650 Fix downloading COCO data
  chainercv/datasets/coco/coco_utils.py
Labels: bug

#657 weight -> width in README
  README.md
Labels: bug

#620 Add FCIS training
  chainercv/experimental/__init__.py
  chainercv/experimental/links/__init__.py
  chainercv/experimental/links/model/fcis/__init__.py
  chainercv/experimental/links/model/fcis/fcis.py
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/experimental/links/model/fcis/fcis_train_chain.py
  chainercv/experimental/links/model/fcis/utils/proposal_target_creator.py
  docs/source/reference/experimental/fcis.rst
  examples/fcis/README.md
  examples/fcis/train.py
  examples/fcis/train_multi.py
  examples/instance_segmentation/README.md
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_train_chain.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/utils_tests/test_proposal_target_creator.py
Labels: feature
