Repository chainer/chainercv, pull requests merged in 2019-02, with the labels that each got.

#743 change range of labels for ADE20K
  chainercv/datasets/ade20k/ade20k_semantic_segmentation_dataset.py
  chainercv/datasets/ade20k/ade20k_utils.py
Labels: enhancement, no-compat

#724 Add FCIS coco demo, training and evaluation
  chainercv/experimental/links/model/fcis/fcis.py
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  examples/fcis/README.md
  examples/fcis/demo.py
  examples/fcis/train_coco_multi.py
  examples/fcis/train_sbd.py
  examples/fcis/train_sbd_multi.py
  examples/instance_segmentation/README.md
  examples/instance_segmentation/eval_coco.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
Labels: feature

#764 Fix PickableSequentialChain.copy()
  chainercv/links/model/pickable_sequential_chain.py
  tests/links_tests/model_tests/test_pickable_sequential_chain.py
Labels: bug

#695 Use f.convert('L') to read grayscale in read_image()
  chainercv/datasets/ade20k/ade20k_semantic_segmentation_dataset.py
  chainercv/datasets/camvid/camvid_dataset.py
  chainercv/datasets/cityscapes/cityscapes_semantic_segmentation_dataset.py
  chainercv/datasets/cub/cub_utils.py
  chainercv/datasets/voc/voc_instance_segmentation_dataset.py
  chainercv/datasets/voc/voc_semantic_segmentation_dataset.py
  chainercv/utils/__init__.py
  chainercv/utils/image/__init__.py
  chainercv/utils/image/read_image.py
  chainercv/utils/image/read_label.py
  docs/source/reference/utils.rst
  tests/utils_tests/image_tests/test_read_image.py
  tests/utils_tests/image_tests/test_read_label.py
Labels: enhancement

#634 Add training part of PSPNet
  chainercv/experimental/links/model/pspnet/pspnet.py
  examples/pspnet/README.md
  examples/pspnet/train_multi.py
  examples/semantic_segmentation/README.md
  examples_tests/pspnet_tests/test_train_multi.sh
  tests/experimental_tests/links_tests/model_tests/pspnet_tests/test_pspnet.py
Labels: feature

#685 Feature Pyramid Networks
  chainercv/links/__init__.py
  chainercv/links/model/fpn/__init__.py
  chainercv/links/model/fpn/faster_rcnn.py
  chainercv/links/model/fpn/faster_rcnn_fpn_resnet.py
  chainercv/links/model/fpn/fpn.py
  chainercv/links/model/fpn/head.py
  chainercv/links/model/fpn/misc.py
  chainercv/links/model/fpn/rpn.py
  docs/source/reference/links.rst
  docs/source/reference/links/fpn.rst
  examples/detection/eval_coco.py
  examples/fcis/README.md
  examples/fpn/README.md
  examples/fpn/demo.py
  examples/fpn/train_multi.py
  examples/ssd/README.md
  examples_tests/detection_tests/test_eval_coco.sh
  examples_tests/fpn_tests/test_demo.sh
  examples_tests/fpn_tests/test_train_multi.sh
  tests/links_tests/model_tests/fpn_tests/__init__.py
  tests/links_tests/model_tests/fpn_tests/test_faster_rcnn.py
  tests/links_tests/model_tests/fpn_tests/test_faster_rcnn_fpn_resnet.py
  tests/links_tests/model_tests/fpn_tests/test_fpn.py
  tests/links_tests/model_tests/fpn_tests/test_head.py
  tests/links_tests/model_tests/fpn_tests/test_rpn.py
Labels: feature

#734 Return rgb when rgba is loaded
  chainercv/utils/image/read_image.py
  tests/utils_tests/image_tests/test_read_image.py
Labels: bug

#769 Enable cv2/InfiniBand hack
  examples/classification/train_imagenet_multi.py
  examples/faster_rcnn/train.py
  examples/fcis/train_coco_multi.py
  examples/fcis/train_sbd.py
  examples/fcis/train_sbd_multi.py
  examples/fpn/train_multi.py
  examples/pspnet/README.md
  examples/pspnet/train_multi.py
  examples/segnet/train.py
  examples/semantic_segmentation/eval_semantic_segmentation_multi.py
  examples/ssd/README.md
  examples/ssd/train.py
  examples/ssd/train_multi.py
Labels: enhancement

#771 Update README for FPN
  README.md
  examples/detection/README.md
  examples/fpn/README.md
Labels: document

#770 Update to v0.12
  docs/source/conf.py
  setup.py
Labels: enhancement

#777 add sort_by_score option to vis_instance_segmentation
  chainercv/visualizations/vis_instance_segmentation.py
  tests/visualizations_tests/test_vis_instance_segmentation.py
Labels: enhancement

#780 fix eval_instance_segmentation_coco when `pred_masks` is empty
  chainercv/evaluations/eval_instance_segmentation_coco.py
  tests/evaluations_tests/test_eval_instance_segmentation_coco.py
Labels: bug

#778 simplify coco instance datasets
  chainercv/datasets/coco/coco_bbox_dataset.py
  chainercv/datasets/coco/coco_instance_segmentation_dataset.py
  chainercv/datasets/coco/coco_instances_base_dataset.py
  tests/datasets_tests/coco_tests/test_coco_instance_segmentation_dataset.py
Labels: enhancement

#779 Prevent mutating input of FeaturePredictor.prepare
  chainercv/links/model/feature_predictor.py
  tests/links_tests/model_tests/test_feature_predictor.py
Labels: bug

#776 set n_gpu * 0.0005 as fcis lr default
  examples/fcis/train_coco_multi.py
  examples/fcis/train_sbd_multi.py
Labels: enhancement

#784 test FCISResNet101 loss
  chainercv/experimental/links/model/fcis/fcis.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
Labels: test

#783 use scales in faster_rcnn_tests
  tests/links_tests/model_tests/faster_rcnn_tests/test_faster_rcnn_train_chain.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_faster_rcnn_vgg.py
Labels: enhancement

#789 add eval_instance_segmentation_multi.py
  examples/instance_segmentation/eval_coco.py
  examples/instance_segmentation/eval_instance_segmentation.py
  examples/instance_segmentation/eval_instance_segmentation_multi.py
  examples/instance_segmentation/eval_sbd.py
Labels: enhancement

#757 DeepLabV3+
  chainercv/links/__init__.py
  chainercv/links/connection/__init__.py
  chainercv/links/connection/separable_conv_2d_bn_activ.py
  chainercv/links/model/deeplab/__init__.py
  chainercv/links/model/deeplab/aspp.py
  chainercv/links/model/deeplab/deeplab_v3_plus.py
  chainercv/links/model/deeplab/xception.py
  docs/source/reference/links/connection.rst
  docs/source/reference/links/deeplab.rst
  examples/deeplab/README.md
  examples/deeplab/demo.py
  examples/deeplab/tf2npz.py
  examples/semantic_segmentation/eval_semantic_segmentation.py
  examples/semantic_segmentation/eval_semantic_segmentation_multi.py
  examples_tests/semantic_segmentation_tests/test_eval_semantic_segmentation.sh
  examples_tests/semantic_segmentation_tests/test_eval_semantic_segmentation_multi.sh
  tests/links_tests/connection_tests/test_separable_conv_2d_bn_activ.py
  tests/links_tests/model_tests/deeplab_tests/test_aspp.py
  tests/links_tests/model_tests/deeplab_tests/test_deeplab_v3_plus.py
Labels: feature

#792 make mask_to_bbox not copy to CPU
  chainercv/utils/mask/mask_to_bbox.py
Labels: enhancement

#798 fix resize when 0 length image is given
  chainercv/transforms/image/resize.py
  tests/transforms_tests/image_tests/test_resize.py
Labels: bug

#801 add sort_by_score in vis_bbox
  chainercv/visualizations/vis_bbox.py
  tests/visualizations_tests/test_vis_bbox.py
Labels: enhancement

#799 add scale_mask
  chainercv/utils/__init__.py
  chainercv/utils/mask/scale_mask.py
  docs/source/reference/utils.rst
  tests/utils_tests/mask_tests/test_scale_mask.py
Labels: enhancement

#805 Add link to deeplab page in document
  docs/source/reference/links.rst
Labels: bug

#811 args --batch-size -> --batchsize in examples
  examples/fcis/train_coco_multi.py
  examples/fcis/train_sbd_multi.py
  examples/pspnet/train_multi.py
Labels: enhancement
