Repository chainer/chainercv, pull requests merged in 2019-04, with the labels that each got.

#807 Use table for the documentation of bbox transforms
  chainercv/transforms/bbox/crop_bbox.py
  chainercv/transforms/bbox/flip_bbox.py
  chainercv/transforms/bbox/resize_bbox.py
  chainercv/transforms/bbox/rotate_bbox.py
  chainercv/transforms/bbox/translate_bbox.py
Labels: document

#809 Change interface of vis_point
  chainercv/visualizations/vis_point.py
  tests/visualizations_tests/test_vis_point.py
Labels: no-compat

#808 change interface of point/transforms
  chainercv/transforms/point/flip_point.py
  chainercv/transforms/point/resize_point.py
  chainercv/transforms/point/translate_point.py
  tests/transforms_tests/point_tests/test_flip_point.py
  tests/transforms_tests/point_tests/test_resize_point.py
  tests/transforms_tests/point_tests/test_translate_point.py
Labels: no-compat

#844 Fix SSD train_multi.py
  .pfnci/config.pbtxt
  examples/ssd/train_multi.py
Labels: bug

#845 use pure_nccl in examples/
  examples/classification/README.md
  examples/classification/train_imagenet_multi.py
  examples/detection/eval_detection_multi.py
  examples/fcis/train_coco_multi.py
  examples/fcis/train_sbd_multi.py
  examples/fpn/train_multi.py
  examples/instance_segmentation/eval_instance_segmentation_multi.py
  examples/pspnet/train_multi.py
  examples/semantic_segmentation/eval_semantic_segmentation_multi.py
  examples/ssd/train_multi.py
Labels: enhancement

#848 Include dockerfile for PFN CI and add tests with chainer master
  .pfnci/cache.sh
  .pfnci/common.sh
  .pfnci/config.pbtxt
  .pfnci/docker/devel-minimal/Dockerfile
  .pfnci/docker/devel/Dockerfile
  .pfnci/examples_tests.sh
  .pfnci/gen_config.py
  .pfnci/tests.sh
  .pfnci/tests_gpu.sh
  chainercv/utils/testing/constant_stub_link.py
  tests/links_tests/connection_tests/test_separable_conv_2d_bn_activ.py
Labels: test

#781 add MaskRCNN
  .pfnci/config.pbtxt
  .pfnci/gen_config.py
  README.md
  chainercv/__init__.py
  chainercv/links/__init__.py
  chainercv/links/model/fpn/__init__.py
  chainercv/links/model/fpn/bbox_head.py
  chainercv/links/model/fpn/faster_rcnn.py
  chainercv/links/model/fpn/faster_rcnn_fpn_resnet.py
  chainercv/links/model/fpn/mask_head.py
  chainercv/links/model/fpn/mask_utils.py
  chainercv/links/model/fpn/misc.py
  chainercv/transforms/image/resize.py
  chainercv/utils/testing/assertions/assert_is_instance_segmentation_link.py
  docs/source/reference/links.rst
  docs/source/reference/links/fpn.rst
  examples/fpn/README.md
  examples/fpn/demo.py
  examples/fpn/train_multi.py
  examples/instance_segmentation/README.md
  examples/instance_segmentation/eval_instance_segmentation.py
  examples_tests/fpn_tests/test_demo.sh
  examples_tests/fpn_tests/test_train_multi.sh
  examples_tests/instance_segmentation_tests/test_eval_instance_segmentation.sh
  examples_tests/instance_segmentation_tests/test_eval_instance_segmentation_multi.sh
  tests/links_tests/model_tests/fpn_tests/test_bbox_head.py
  tests/links_tests/model_tests/fpn_tests/test_faster_rcnn.py
  tests/links_tests/model_tests/fpn_tests/test_faster_rcnn_fpn_resnet.py
  tests/links_tests/model_tests/fpn_tests/test_mask_head.py
  tests/links_tests/model_tests/fpn_tests/test_mask_utils.py
  tests/transforms_tests/image_tests/test_resize.py
Labels: feature, no-compat

#840 add fcis examples_tests
  examples_tests/fcis_tests/test_demo.sh
  examples_tests/fcis_tests/test_train_coco_multi.sh
  examples_tests/fcis_tests/test_train_sbd.sh
  examples_tests/fcis_tests/test_train_sbd_multi.sh
Labels: enhancement, test
