Repository chainer/chainercv, pull requests merged in 2019-06, with the labels that each got.

#885 fix doc build
  docs/rtd_conda.yml
  readthedocs.yml
Labels: document

#886 Remove deprecated TransformDataset
  chainercv/datasets/__init__.py
  chainercv/datasets/transform_dataset.py
  tests/datasets_tests/test_transform_dataset.py
Labels: no-compat

#889 `example/ssd/train_multi.py` MultiboxTrainChain is not set communicator?
  examples/ssd/train_multi.py
Labels: bug

#891 update to v0.13.1
  docs/source/conf.py
  setup.py
Labels: enhancement

#890 Stop installing unzip in pfnCI
  .pfnci/examples_tests.sh
  .pfnci/tests.sh
Labels: test

#893 Fix typos in experimental datasets
  chainercv/chainer_experimental/datasets/sliceable/sliceable_dataset.py
  chainercv/chainer_experimental/datasets/sliceable/transform_dataset.py
Labels: bug

#894 refine error message in ps_roi functions
  chainercv/functions/ps_roi_average_align_2d.py
  chainercv/functions/ps_roi_average_pooling_2d.py
  chainercv/functions/ps_roi_max_align_2d.py
  chainercv/functions/ps_roi_max_pooling_2d.py
Labels: enhancement

#896 Fix typos
  chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py
Labels: document

#887 Revert "Merge pull request #885 from knorth55/fix-doc-build"
  docs/rtd_conda.yml
  readthedocs.yml
Labels: document
