Repository chainer/chainercv, pull requests merged in 2019-05, with the labels that each got.

#862 fix instance_segmentation readme
  examples/instance_segmentation/README.md
Labels: document

#857 Use with block instead of setting global config
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis_resnet101.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_faster_rcnn_vgg.py
  tests/links_tests/model_tests/faster_rcnn_tests/test_region_proposal_network.py
  tests/links_tests/model_tests/faster_rcnn_tests/utils_tests/test_proposal_creator.py
  tests/transforms_tests/image_tests/test_resize.py
  tests/transforms_tests/image_tests/test_rotate.py
Labels: bug

#863 DetectionVisReport save tight figure
  chainercv/extensions/vis_report/detection_vis_report.py
Labels: enhancement

#866 use - isntead of _
  examples/classification/train_imagenet_multi.py
Labels: document

#865 pfnCI on CuPy repository
  .pfnci/common.sh
Labels: test

#832 Support Chainer-style initialization in TransformDataset
  chainercv/chainer_experimental/datasets/sliceable/transform_dataset.py
  tests/chainer_experimental_tests/datasets_tests/sliceable_tests/test_getter_dataset.py
  tests/chainer_experimental_tests/datasets_tests/sliceable_tests/test_sliceable_dataset.py
  tests/chainer_experimental_tests/datasets_tests/sliceable_tests/test_transform_dataset.py
Labels: no-compat

#872 Update readme
  examples/detection/README.md
  examples/instance_segmentation/README.md
  examples/semantic_segmentation/README.md
Labels: document

#874 refactor eval_imagenet.py
  examples/classification/eval_imagenet.py
Labels: enhancement

#875 refactor eval_semantic_segmentation
  examples/semantic_segmentation/eval_semantic_segmentation.py
  examples/semantic_segmentation/eval_semantic_segmentation_multi.py
Labels: enhancement

#871 refactor eval codes
  examples/detection/eval_detection.py
  examples/detection/eval_detection_multi.py
  examples/instance_segmentation/eval_instance_segmentation.py
  examples/instance_segmentation/eval_instance_segmentation_multi.py
Labels: enhancement

#878 update semantic_segmentation/README.md
  examples/semantic_segmentation/README.md
Labels: document

#879 add test_xception.py
  tests/links_tests/model_tests/deeplab_tests/test_xception.py
Labels: test

#803 Change doc style of vis_*
  chainercv/visualizations/vis_bbox.py
  chainercv/visualizations/vis_image.py
  chainercv/visualizations/vis_instance_segmentation.py
  chainercv/visualizations/vis_semantic_segmentation.py
Labels: document, enhancement

#877 add arg --dataset in examples demo
  examples/deeplab/README.md
  examples/deeplab/demo.py
  examples/faster_rcnn/demo.py
  examples/fcis/README.md
  examples/fpn/demo.py
  examples/pspnet/README.md
  examples/pspnet/demo.py
  examples/segnet/demo.py
  examples/ssd/demo.py
  examples/yolo/demo.py
Labels: enhancement

#833 Remove # of keys support from Sliceable
  chainercv/chainer_experimental/datasets/sliceable/getter_dataset.py
  chainercv/chainer_experimental/datasets/sliceable/transform_dataset.py
  tests/chainer_experimental_tests/datasets_tests/sliceable_tests/test_getter_dataset.py
  tests/chainer_experimental_tests/datasets_tests/sliceable_tests/test_transform_dataset.py
Labels: no-compat

#868 Support MN mode for evaluators
  chainercv/extensions/evaluator/detection_coco_evaluator.py
  chainercv/extensions/evaluator/detection_voc_evaluator.py
  chainercv/extensions/evaluator/instance_segmentation_coco_evaluator.py
  chainercv/extensions/evaluator/instance_segmentation_voc_evaluator.py
  chainercv/extensions/evaluator/semantic_segmentation_evaluator.py
  tests/extensions_tests/evaluator_tests/test_detection_coco_evaluator.py
  tests/extensions_tests/evaluator_tests/test_detection_voc_evaluator.py
  tests/extensions_tests/evaluator_tests/test_instance_segmentation_coco_evaluator.py
  tests/extensions_tests/evaluator_tests/test_instance_segmentation_voc_evaluator.py
  tests/extensions_tests/evaluator_tests/test_semantic_segmentation_evaluator.py
Labels: enhancement

#846 Use Ours and Original when reporting performance
  examples/classification/README.md
  examples/deeplab/README.md
  examples/faster_rcnn/README.md
  examples/pspnet/README.md
  examples/segnet/README.md
  examples/semantic_segmentation/README.md
  examples/ssd/README.md
  examples/yolo/README.md
Labels: document

#797 add PS RoI Max Pooling
  chainercv/functions/__init__.py
  chainercv/functions/ps_roi_max_pooling_2d.py
  docs/source/reference/functions.rst
  tests/functions_tests/test_ps_roi_max_pooling.py
Labels: feature

#883 version up to v0.13
  docs/source/conf.py
  setup.py
Labels: enhancement

#884 Update readme
  README.md
Labels: document
