Repository chainer/chainercv, pull requests merged in 2019-03, with the labels that each got.

#820 Fix docstring of DirectoryParsingLabelDataset
  chainercv/datasets/directory_parsing_label_dataset.py
Labels: document

#814 Show the cause of ValueError
  chainercv/links/model/pickable_sequential_chain.py
  tests/links_tests/model_tests/test_pickable_sequential_chain.py
Labels: enhancement

#826 Fix inference configuration on ADE20K in DeepLab
  chainercv/links/model/deeplab/deeplab_v3_plus.py
  examples/deeplab/README.md
  examples/deeplab/tf2npz.py
Labels: bug

#806 change assert_is_point, assert_is_point_dataset, CUB datasets
  chainercv/datasets/__init__.py
  chainercv/datasets/cub/cub_keypoint_dataset.py
  chainercv/datasets/cub/cub_label_dataset.py
  chainercv/datasets/cub/cub_utils.py
  chainercv/utils/testing/assertions/assert_is_point.py
  chainercv/utils/testing/assertions/assert_is_point_dataset.py
  tests/datasets_tests/cub_tests/test_cub_keypoint_dataset.py
  tests/datasets_tests/cub_tests/test_cub_label_dataset.py
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_point.py
  tests/utils_tests/testing_tests/assertions_tests/test_assert_is_point_dataset.py
Labels: enhancement, no-compat

#804 Change doc style of eval_*
  chainercv/evaluations/eval_detection_voc.py
  chainercv/evaluations/eval_instance_segmentation_voc.py
  chainercv/evaluations/eval_semantic_segmentation.py
Labels: document, enhancement

#837 update readme
  README.md
Labels: document

#834 fix missing link in doc
  docs/source/reference/datasets.rst
Labels: bug

#836 Add argument of `alpha` to `MixUpSoftLabelDataset`
  chainercv/datasets/mixup_soft_label_dataset.py
  tests/datasets_tests/test_mixup_soft_label_dataset.py
Labels: enhancement

#839 Create .lock directory
  chainercv/datasets/ade20k/ade20k_utils.py
  chainercv/datasets/camvid/camvid_dataset.py
  chainercv/datasets/coco/coco_utils.py
  chainercv/datasets/cub/cub_utils.py
  chainercv/datasets/online_products/online_products_dataset.py
  chainercv/datasets/sbd/sbd_utils.py
  chainercv/datasets/voc/voc_utils.py
Labels: enhancement

#835 Change links to override forward
  chainercv/experimental/links/model/fcis/fcis.py
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/experimental/links/model/fcis/fcis_train_chain.py
  chainercv/experimental/links/model/pspnet/pspnet.py
  chainercv/experimental/links/model/yolo/yolo_v2_tiny.py
  chainercv/links/connection/conv_2d_activ.py
  chainercv/links/connection/conv_2d_bn_activ.py
  chainercv/links/connection/seblock.py
  chainercv/links/connection/separable_conv_2d_bn_activ.py
  chainercv/links/model/deeplab/aspp.py
  chainercv/links/model/deeplab/deeplab_v3_plus.py
  chainercv/links/model/deeplab/xception.py
  chainercv/links/model/faster_rcnn/faster_rcnn.py
  chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py
  chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py
  chainercv/links/model/faster_rcnn/region_proposal_network.py
  chainercv/links/model/fpn/faster_rcnn.py
  chainercv/links/model/fpn/fpn.py
  chainercv/links/model/fpn/head.py
  chainercv/links/model/fpn/rpn.py
  chainercv/links/model/pickable_sequential_chain.py
  chainercv/links/model/pixelwise_softmax_classifier.py
  chainercv/links/model/resnet/resblock.py
  chainercv/links/model/segnet/segnet_basic.py
  chainercv/links/model/ssd/multibox.py
  chainercv/links/model/ssd/normalize.py
  chainercv/links/model/ssd/ssd.py
  chainercv/links/model/ssd/ssd_vgg16.py
  chainercv/links/model/vgg/vgg16.py
  chainercv/links/model/yolo/yolo_base.py
  chainercv/links/model/yolo/yolo_v2.py
  chainercv/links/model/yolo/yolo_v3.py
  chainercv/utils/testing/constant_stub_link.py
  docs/source/reference/experimental/fcis.rst
  docs/source/reference/experimental/yolo.rst
  docs/source/reference/links/classifier.rst
  docs/source/reference/links/deeplab.rst
  docs/source/reference/links/faster_rcnn.rst
  docs/source/reference/links/fpn.rst
  docs/source/reference/links/segnet.rst
  docs/source/reference/links/ssd.rst
  docs/source/reference/links/yolo.rst
  examples/faster_rcnn/README.md
  examples/fpn/train_multi.py
  examples/pspnet/train_multi.py
  examples/ssd/train.py
  examples/ssd/train_multi.py
  tests/experimental_tests/links_tests/model_tests/fcis_tests/test_fcis.py
  tests/links_tests/model_tests/faster_rcnn_tests/dummy_faster_rcnn.py
  tests/links_tests/model_tests/fpn_tests/test_faster_rcnn.py
  tests/links_tests/model_tests/fpn_tests/test_fpn.py
  tests/links_tests/model_tests/ssd_tests/test_ssd.py
  tests/links_tests/model_tests/test_feature_predictor.py
  tests/links_tests/model_tests/test_pixelwise_softmax_classifier.py
  tests/links_tests/model_tests/yolo_tests/test_yolo_base.py
Labels: enhancement

#795 rename psroi_pooling -> ps_roi_average_pooling and refactor
  chainercv/experimental/links/model/fcis/fcis_resnet101.py
  chainercv/functions/__init__.py
  chainercv/functions/ps_roi_average_pooling_2d.py
  chainercv/functions/psroi_pooling_2d.py
  docs/source/reference/functions.rst
  tests/functions_tests/test_ps_roi_average_pooling_2d.py
Labels: enhancement
